apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rag-nov6-2 
  janus-idp.io/tekton: rag-nov6-2
  backstage.io/kubernetes-id: rag-nov6-2
  backstage.io/kubernetes-namespace: rag-nov6-2 
  app.kubernetes.io/part-of: rag-nov6-2
resources: 
- application-dev.yaml